### ISSUE TITLE
0002 Half-Bit Adder Review request

### ISSUE THREAD

**Issue by vineetarath** [mathscapes/DecodeVector#16]
@apoorva-a98, do review my current 0002 file - the half-bit adder problem https://github.com/vineetarath/dv.pset/blob/998bdf3c41c2c750c4c5132d7421d65a4e04aee3/0002/0002-%201-Bit%20Half%20Adder.jpeg

**Comment by indirectjump** [comment]
* Maybe refer the file by giving a link here. It will be easier for the reviewer.
* Assign reviewer from the right sidebar (under Assignees).
* Add relevant labels for organization sake.

**Comment by grvashu** [comment]
Assign reviewer from the right sidebar (under Assignees).

**Comment by grvashu** [comment]
Add relevant labels for organization sake.

**Comment by vineetarath** [comment]
@grvashu, some of my files still have a .js or .DS store file that is being created when I start uploading via github desktop - don't understand why :(

**Comment by indirectjump** [comment]
Find out why it is happening and resolve it.

**Comment by MasterPranjal** [comment]
Your 'S' is correct. But what is 'C'?

**Comment by MasterPranjal** [comment]
.DS Store is Desktop Services Store. It is created and maintained by the Finder application in every folder. It is mostly created in MAC. I don't know about windows.
