### ISSUE TITLE
Display Order of Daily Rating Log: Please vote here, stating reason for preference.

### ISSUE THREAD

**Issue by vineetarath** [mathscapes/DecodeVector#18]
How many of you would prefer A vs.B? Where 
A: is most recent rating row first and 
B: earliest rating row first? To elucidate:

A: 
| 19/04/2018 | 1   | 7   | 0 | 3    | 3   | 9      | 1:`0001` `0002` `0003` |
| 18/04/2018 | 1   | 6   | 0 | 3    | 3   | 9      | 1:`0001` `0002` `0003` |
| 17/04/2018 | 1   | 5   | 0 | 3    | 3   | 9      | 1:`0001` `0002` `0003` |
| 16/04/2018 | 1   | 4   | 0 | 3    | 3   | 9      | 1:`0001` `0002` `0003` |

vs.

B
| 16/04/2018 | 1   | 4   | 0 | 3    | 3   | 9      | 1:`0001` `0002` `0003` |
| 17/04/2018 | 1   | 5   | 0 | 3    | 3   | 9      | 1:`0001` `0002` `0003` |
| 18/04/2018 | 1   | 6   | 0 | 3    | 3   | 9      | 1:`0001` `0002` `0003` |
| 19/04/2018 | 1   | 7   | 0 | 3    | 3   | 9      | 1:`0001` `0002` `0003` |

@vineetarath : Prefer format A since shows most updated state at first glance
@grvashu :
@MasterPranjal :
@simraan9 :
@apoorva-a98 :

**Comment by indirectjump** [comment]
A

**Comment by MasterPranjal** [comment]
A: it is better

**Comment by indirectjump** [comment]
@vineetarath, suggestion accepted. Thank you.
@MasterPranjal @simraan9 @apoorva-a98 Please take a note.
Closing this issue.

**Comment by simraan9** [comment]
Alright
