### ISSUE TITLE
[Important] Peer review

### ISSUE THREAD

**Issue by indirectjump** [mathscapes/DecodeVector#20]
Hello everyone, I'm continuing to see discrepancies in the process of recording your pset progress. Can I ask each one of you to verify one other progress?

- [x] Vineeta and Simran to review Apoorva's progress
- [ ] Simran and Apoorva to review Pranjal's progress
- [ ] Pranjal and Apoorva to review Simran's progress
- [ ] Apoorva and Simran to review Vineeta's progress

Here's what you need to review:
- Check if the member wiki contains a table like on example page (but starting with most recent rows first and each record has cumulative stats). You may refer Vineeta's table for reference. Also refer https://github.com/mathscapes/DecodeVector/issues/18 to understand a recent change.
- Check if the member has actually committed each problem on GitHub on the date specified in the table.
- Check if every solution is actually correct.
- Check if the table has a row of days when the member has not done any problem.
- The rating is correctly calculated for each day as per the http://dv.mathscapes.xyz/sub/rating-system.

Please coordinate here and finalize your wikis to get ready for the peer review. And please comment here if you find any discrepancies. The reviewers will be held responsible if they fail to spot the issues in the reviewee wiki.

Please complete this review latest by the end of the week. 

Last but not the least, feel free to design a better tracking and logging mechanism for your PSET progress and DV rating.

**Comment by vineetarath** [comment]
Hi @apoorva-a98 , @MasterPranjal , @simraan9 , @grvashu !

Please collaborate with your co-reviewer and update the rating on the gdrive spreadsheet shared separately.

Simran and I have reviewed Apoorva's Progress on PSet. @apoorva-a98 , kindly take the next 2 days to manage discrepancies listed in the document link shared earlier, so that we may revisit and update the same.

**Comment by indirectjump** [comment]
Thank you @vineetarath and @simraan9 for reviewing Apoorva's standing.
What is the status of remaining reviews?
