### ISSUE TITLE
Can't figure out why my table doesn't look like a table

### ISSUE THREAD

**Issue by simraan9** [mathscapes/DecodeVector#21]
I know this is probably stupid but I looked at the example page and im still unable to figure out why my page table is messed up! I'm messing up the html aren't I? I fixed my entries according to the uploads
Also, great formula. My points are decelerating like crazy and it's very motivating

**Comment by simraan9** [comment]
no wait got it

**Comment by vineetarath** [comment]
we can discuss when we review apoorva's around 4 pm
