### ISSUE TITLE
@vineetarath Incorrect marking in wiki 

### ISSUE THREAD

**Issue by indirectjump** [mathscapes/DecodeVector#34]
0041 is worth 0 points, not 1.
Correct your wiki.

**Comment by vineetarath** [comment]
#### Cumulative Stats
| Date       | D   | T   | L | P    | S   | Rating | Problems solved |
| :--------- | --- | --- | - | ---- | --- | ------ | :-------------- |
| 22/05/2018 | 15  | 42  | 0 | 15   | 15  |  8     | 0:`0041` |
| 21/05/2018 | 14  | 41  | 0 | 14   | 15  |  7     | 1:`0029` |
| 20/05/2018 | 13  | 40  | 0 | 13   | 14  |  5     | 0        | 

5 + 2*15 - 42 +15 = 8

Rating is correct. Problem points were wrong, updated that. Works?
