### ISSUE TITLE
@MasterPranjal Incorrect marking in wiki

### ISSUE THREAD

**Issue by indirectjump** [mathscapes/DecodeVector#35]
![screen shot 2018-05-24 at 12 35 29 am](https://user-images.githubusercontent.com/2363826/40445728-92b31a4e-5eea-11e8-87d1-2a56f9e31cb3.png)
Multiple entries for 13/05/2018. Fix it.

**Comment by MasterPranjal** [comment]
corrected for now. Will check again in the evening.
