### ISSUE TITLE
Factorial digit sum 

### ISSUE THREAD

**Issue by simraan9** [mathscapes/DecodeVector#36]
Probably messing this from the start, probably stuck on the last step.
![image](https://user-images.githubusercontent.com/22179784/40565149-01169e58-6089-11e8-853b-9d381df71d30.png)

love the uPSET pun.

**PSET Code**
[eg. `0066`]

**Comment by indirectjump** [comment]
Not sure what you're asking here.
The final output is the sum of digits in 100! not the digit themselves.
Also, are you sure that these are the digits of 100!?

**Comment by simraan9** [comment]
Yes, I am sure. Thank you!
