### ISSUE TITLE
0059: Error in question

### ISSUE THREAD

**Issue by vineetarath** [mathscapes/DecodeVector#39]
"Write a computer program which computes if this dumb monkey can climb on a pillar or not. Every time this monkey climbs, it goes up 3 ft, and slips by 1 ft, which means he is essentially climbing only 1 ft. He can only climb successfully if exactly 3 fts are remaining from the topmost point."

In the above question, if he climbs 3 ft, and slips by 1 ft, he is climbing 2 ft, not 1.

**Comment by indirectjump** [comment]
Thanks for pointing it out. 
Yes, the monkey climbs 3ft every time and slips by 1ft. So effectively climbing 2ft.

I will update it.
