### ISSUE TITLE
0023: superscript not rendering properly

### ISSUE THREAD

**Issue by vineetarath** [mathscapes/DecodeVector#40]
In the 0023: Sum Square Difference question, ^2 appears as the last digit of the number i.e. 12+22+...+102=385 instead of 1^2+ 2^2... etc.

![screen shot 2018-06-15 at 8 51 40 pm](https://user-images.githubusercontent.com/36075796/41476045-033e68f4-70de-11e8-9c4a-22e5f97a1908.png)

**Comment by indirectjump** [comment]
Thanks, will fix this.
