### ISSUE TITLE
0001 - Review Request

### ISSUE THREAD

**Issue by vineetarath** [mathscapes/DecodeVector#7]
No issues, just updating here.

**Comment by indirectjump** [comment]
Folder names do not have extensions (like you have put .js after 0001).

Only acceptable folder names are:
* 0001
* 0001: Moving ball <-- Now accepted.

Get rid of .DS_Store file from your repo.

And the format was meant to guide you about adding title and body. You have instead put everything in the body of the issue. I have edited it.

Also assign your leader if you want someone to review.
